# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.1
loader_version=0.16.8

#Fabric api
fabric_version=0.114.1+1.21.3

# Mod Properties
mod_version = 1.2.0-1.21.3
maven_group = io.github.hakim
archives_base_name = impaled

#Other Dependencies
findbugs_version = 3.0.2
jb_annotations_version = 15.0
apiguardian_version = 1.0.0
vanguard_version = 1.0.+
mialeemisc_version = 1.0.39

#Publishing - Fork by Hakim
owners = Hakim
license_header = ARR
# Remove publishing IDs for the fork - these belong to the original mod
# curseforge_id = 478843
# modrinth_id = AiHAhIP5
curseforge_versions = 1.21.3
cf_requirements = fabric-api
release_type = release
