[versions]
cca = "6.0.0-beta.3"
enchancement = "1.20.6-r7"
mialib = "1.0.92+1.20.6"
midnightLib = "1.5.5-fabric"
modmenu = "10.0.0-beta.1"
tooltipFix = "1.1.1-1.20"

[libraries]
cca-base = { module = "org.ladysnake.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca-entity = { module = "org.ladysnake.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
cca-world = { module = "org.ladysnake.cardinal-components-api:cardinal-components-world", version.ref = "cca" }
cca-scoreboard = { module = "org.ladysnake.cardinal-components-api:cardinal-components-scoreboard", version.ref = "cca" }
enchancement = { module = "maven.modrinth:enchancement", version.ref = "enchancement" }
mialib = { module = "xyz.amymialee:mialib", version.ref = "mialib" }
midnightLib = { module = "maven.modrinth:midnightlib", version.ref = "midnightLib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu"}
tooltipFix = { module = "maven.modrinth:tooltipfix", version.ref = "tooltipFix" }

[bundles]
enchancement = [
    "cca-base",
    "cca-entity",
    "cca-world",
    "enchancement",
    "midnightLib",
    "tooltipFix"
]
